name: Auto Comment on PR #3

on:
  workflow_dispatch:  # Manual trigger
  # You can also add other triggers like:
  # schedule:
  #   - cron: '0 */6 * * *'  # Every 6 hours
  # pull_request:
  #   types: [opened, synchronize]
  #   branches: [main]
permissions:
  issues: write
  pull-requests: write
jobs:
  comment-on-pr:
    runs-on: ubuntu-latest
    
    steps:
      - name: Comment on PR #3
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = 3;
            const comment = '@pytorchbot merge -f "true"';
            
            try {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                body: comment
              });
              
              console.log(`Successfully commented on PR #${prNumber}`);
            } catch (error) {
              console.error(`Failed to comment on PR #${prNumber}:`, error);
              throw error;
            }
